---
extends: airbnb-base
env:
  browser: true
  commonjs: true
  es6: true
  mocha: true
plugins:
  - no-only-tests
rules:
  max-len:
    - warn
    - 200
  max-classes-per-file: 'off'
overrides:
  - files: "*.test.js"
    rules:
      no-unused-expressions: "off"
