version: 2

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      # trigger a release on production
      # after the release it will tag on github on the form x.x.x
      - release-tag:
          requires:
            - build
          filters:
            branches:
              only:
                - master

jobs:
  build:
    docker:
      - image: circleci/node:12.18

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}-{{checksum "package-lock.json"}}

      - run: sudo npm install -g npm
      - run: npm ci

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}-{{checksum "package-lock.json"}}

      - run:
          name: run tests incl coverage
          command: npm run test
      - run: npm run lint

  release-tag:
    docker:
      - image: circleci/node:12.18

    working_directory: ~/repo

    steps:
      - checkout

      # # Download and cache dependencies
      # - restore_cache:
      #     keys:
      #     - v1-dependencies-{{ checksum "package.json" }}-{{checksum "package-lock.json"}}

      - run: sudo npm install -g npm
      - run: npm ci
      - run: npm run dist

      # - save_cache:
      #     paths:
      #       - node_modules
      #     key: v1-dependencies-{{ checksum "package.json" }}-{{checksum "package-lock.json"}}

      - run:
          name: git config
          command: |
            git config credential.helper 'cache --timeout=120'
            git config user.email "no-reply@identity.org"
            git config user.name "ci deployer"
            git config --global push.default simple
            git branch --set-upstream-to origin/$CIRCLE_BRANCH

      - run:
          name: version
          command: npm version patch --git-tag-version false

      - run:
          name: tag
          command: npm run tag
